package orangeHRM;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
public class EmployeeReport {

	public static void main(String[] args) {
		System.setProperty("webdriver.chrome.driver","C:\\Users\\hp\\Desktop\\selenuim jars\\chromedriver_win32\\chromedriver.exe");

		 WebDriver driver = new ChromeDriver();
		 driver.manage().windows().maximize();
		 driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login");
		 
		// Enter the username and password for the admin user
	        WebElement usernameField = driver.findElement(By.id("txtUsername"));
	        usernameField.sendKeys("admin");
	        WebElement passwordField = driver.findElement(By.id("txtPassword"));
	        passwordField.sendKeys("admin123");
	        
	        // Click on the login button
	        WebElement loginButton = driver.findElement(By.id("btnLogin"));
	        loginButton.click();
	        
	     // Navigate to the employee report generation page
	        WebElement pimMenu = driver.findElement(By.xpath("[@id='menu_pim_viewPimModule']"));
	        pimMenu.click();
	        WebElement reportsMenu = driver.findElement(By.xpath("[@id='menu_core_viewDefinedPredefinedReports']"));
	        reportsMenu.click();
	        
	        // Verify that the employee report generation page is displayed
	        WebElement pageTitle = driver.findElement(By.xpath("h1[text()='Predefined Reports']"));
	        if (pageTitle.isDisplayed()) {
	            System.out.println("Employee Report Generation page is accessible.");
	        } else {
	            System.out.println("Employee Report Generation page is not accessible.");
	            driver.quit();
	            return;
	        }

	        // Generate an employee report by selecting a report type and clicking on the 'View' button
	        WebElement reportType = driver.findElement(By.xpath("//select[@id='report_report_type']"));
	        reportType.sendKeys("PIM Sample Report"); // Replace with the desired report type
	        WebElement viewButton = driver.findElement(By.id("viewBtn"));
	        viewButton.click();
	        
	        // Verify that the report is generated by checking the presence of the report data
	        WebElement reportData = driver.findElement(By.xpath("//table[@id='resultTable']"));
	        if (reportData.isDisplayed()) {
	            System.out.println("Employee Report generated successfully.");
	        } else {
	            System.out.println("Employee Report generation failed.");
	        }

	        // Close the browser
	        driver.quit();
	}

}
